# Generated by Django 5.2.7 on 2025-11-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('book', 'Libro'), ('movie', 'Película')], max_length=10)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
